name: Build

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install runtime dependencies only
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate app boots
        run: |
          python -c "import uvicorn"
